VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes

# Pointing device configuration
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = combined
SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_COMBINED = yes

# Enable I2C for Cirque trackpad
I2C_DRIVER_ENABLE = yes
